### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by SivakumarNuthalapati** [anmolrajpal/vehicle-info#1]
root@kali:~# python vehicle-info.py MH04GM9660
Traceback (most recent call last):
  File "vehicle-info.py", line 1, in <module>
    import pytesseract
ImportError: No module named pytesseract
 
AFTER THIS INSTALLED - pip install pytesseract

NExt Error 

root@kali:~# python vehicle-info.py MH04GM9660
Traceback (most recent call last):
  File "vehicle-info.py", line 7, in <module>
    import cv2
ImportError: No module named cv2

pip install opencv-python

next this error came 

root@kali:~# python vehicle-info.py MH04GM9660
Resolving Captcha
Traceback (most recent call last):
  File "vehicle-info.py", line 54, in <module>
    captcha_text = resolve(img)
  File "vehicle-info.py", line 41, in resolve
    return pytesseract.image_to_string(enhancedImage)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 345, in image_to_string
    }[output_type]()
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 344, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 253, in run_and_get_output
    run_tesseract(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 225, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path

**Comment by anmolrajpal** [comment]
Hi, as mentioned in the error, You have to tesseract in your path variable. I think you’re using Linux. I suppose you should google how to add putesseract in your path variable. 

Best Regards,
Anmol Rajpal

**Comment by SivakumarNuthalapati** [comment]
yes installed all those and set all after that this error came once check it

root@kali:~# python vehicle-info.py MH04GM9660
Traceback (most recent call last):
  File "vehicle-info.py", line 31, in <module>
    viewstate = soup.select('input[name="javax.faces.ViewState"]')[5]['value']
IndexError: list index out of range
root@kali:~#

**Comment by SivakumarNuthalapati** [comment]
after some try this will came 

root@kali:~# python vehicle-info.py MH04GM9660
Resolving Captcha
('OCR Result => ', u'XSX16Y')
XSX16Y
{'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Faces-Request': 'partial/ajax', 'Origin': 'https://vahan.nic.in', 'Accept': 'application/xml, text/xml, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15', 'Host': 'vahan.nic.in', 'Referer': 'https://vahan.nic.in/nrservices/faces/user/searchstatus.xhtml', 'Cookie': 'JSESSIONID=86EC285597976A7514F73F74A3B4A71C.worker3; SERVERID_7081=vahanapi_7081; SERVERID_7082=nrservice_7082', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
('\nCookie JSESSIONID => ', '86EC285597976A7514F73F74A3B4A71C.worker3')

Data => 

{'javax.faces.ViewState': u'oUwtj40CGa7/uHZXPD1FsxPyE354CbIRNalnHtFdYguLsVTWOHijsJK2hkMNf6vOOQu0MMRPmVALfypDVr06W65Ik/DXFRdMtn4M2O0NJ8wnXDHaD+RznF0NwwFeqqfPGPrRnmXVeo1u+gpS/5vPoJBAzi/64bV30oclCzobLEmsD+EtOQZRxOR11SjyXN/2Z8pvVCDXInrhssmyElyJjwtZ0ZKXwXkNWLadJ3UOC05J7+rj+l3j9IGWKMVPkaWQAGySniXZfNWDOKTWOljTMJVl3KOMuLUH0bBLfpiOAiBQHWWoTFlUhT0v55bEfxmrTrIzU+qcQxgkh1vv3TOaCl4zcX3NP7EtlHDd13FTb+35JnHx3he2L7yxdBsedxOiL2+KmhN0TY92ROcADwKgA8qcjOBXE02/cC0S/YWNeA9IofGAE4bWjxrF/3jRLB8qxUkQJEWHAROYcUe0bi+j/Qk/cwt1RPGJ+Kr3Y5ZyjZFvX12GjKvhzZJ5CX/rfGqD21TD3KIl3WjvUwu04i5hNwH/aR717BLmDtBHE/1X79WOVvOLTkt5qZaLbYnOfaewHBX6wfvCKxiqIFTEjYw+K+p+K4e6VXJ/myhyWFzKYblNuXXYVe7cF8w7kA3n8/1WNJDKQ471qB3FsOIatkkmWhKl9voMALU8OCVyvsDqhzsoiIHmk7ztfq7QWRvLz3dSgSx3W5XywlNwvYTgeXCCyiorBu/h1ylmzY99iwjA03aMzAic25590UD6UWzdLYHXKG5f9QMTIK3RZ9Z5hsZbyV0vdHcHSa1tj0/ly4T54Q1bOQw48K6oOboTVxoWEu2c1k2/z639ntWcfTLH0U+5nlnzLNM58oHh1lfuIWmwvZl170wP0xezw2djewGPvBa2iOTSGeDansmkwQ/I/nlXIqFs0Ze2R6qiBhEMl2ZxdQJtXnsEdr0XgSh8UtNy7yEoNHgbda8VCGrL62wu1vONJf6CTteGDiYyNZFT+Xovt/7pDh3MaXp6B4czdN/6ykX1aSXGwnjfNFAG2yVDaCaXQKeA2y9SUE8JSudNyUFtq8JhYXHS/7BwpY4deJlrLazv3jU8vHDGzOZO+1dJrIXH9wcdmWbc5B4lnaUu14wovls=', 'j_idt32': '', 'javax.faces.partial.render': 'rcDetailsPanel resultPanel userMessages capatcha txt_ALPHA_NUMERIC', 'txt_ALPHA_NUMERIC': u'XSX16Y', 'javax.faces.partial.execute': '@all', 'javax.faces.source': u'j_idt43', u'j_idt43': u'j_idt43', 'javax.faces.partial.ajax': 'true', 'masterLayout': 'masterLayout', 'regn_no1_exact': 'MH04GM9660'}

POST Request -> Response =>

<Response [404]>
Mark: postResponse soup => 
<html>
 <head>
  <title>
   Vahan Sewa
  </title>
  <meta content="0; url=https://vahan.nic.in/nrservices/" http-equiv="REFRESH"/>
 </head>
</html>
<body>
 <center>
  <br/>
  <br/>
  <br/>
  <br/>
  <font color="red" size="8">
   Please wait....
  </font>
 </center>
</body>

Table Soup =>

**Comment by SivakumarNuthalapati** [comment]
and again same issue 

root@kali:~# python vehicle-info.py TS09XX1234
Traceback (most recent call last):
  File "vehicle-info.py", line 31, in <module>
    viewstate = soup.select('input[name="javax.faces.ViewState"]')[0]['value']
IndexError: list index out of range
root@kali:~#

**Comment by anmolrajpal** [comment]
Yes, you’ve achieved the expected output. I’ve logged the most important information. Now the expected output should be at bottom but the tabular data isn’t appending in the result. 

Now I want you to open your Browser - safari or firefox. 
Open the vahan website mentioned in this project. Open “Inspect Element” ->  open Network Tab and monitor all requests and response for each URL. 
Check and verifies all cookies. 

Now our task is to make our python script work similarly to the web version. 

If it’s difficult to contact on email, we can contact directly through phone numbers or whatsapp or whatever you want. Just let me know. It’s a very good project. I hope we’ll be able to achieve success in this. 

Best Regards,
Anmol Rajpal

**Comment by SivakumarNuthalapati** [comment]
hi thank you 

yes further work need to achieve

**Comment by manideepkamtala** [comment]
When i'm running getting this 


Resolving Captcha
OCR Result =>  QQBZ36
QQBZ36
{'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Accept': 'application/xml, text/xml, */*; q=0.01', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'vahan.nic.in', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15', 'Cookie': 'JSESSIONID=15ED9489F2F8F9954A17FEB1050CDD49.worker3; SERVERID_7081=vahanapi_7081; SERVERID_7082=nrservice_7082', 'X-Requested-With': 'XMLHttpRequest', 'Faces-Request': 'partial/ajax', 'Origin': 'https://vahan.nic.in', 'Referer': 'https://vahan.nic.in/nrservices/faces/user/searchstatus.xhtml', 'Connection': 'keep-alive'}

Cookie JSESSIONID =>  15ED9489F2F8F9954A17FEB1050CDD49.worker3

Data => 

{'javax.faces.partial.ajax': 'true', 'javax.faces.source': 'j_idt44', 'javax.faces.partial.execute': '@all', 'javax.faces.partial.render': 'rcDetailsPanel resultPanel userMessages capatcha txt_ALPHA_NUMERIC', 'j_idt44': 'j_idt44', 'masterLayout': 'masterLayout', 'regn_no1_exact': '-f', 'txt_ALPHA_NUMERIC': 'QQBZ36', 'javax.faces.ViewState': 'WWmudkRrEYuguMLpg7zBzQGCcuJvlOxn35lwj0ayaB1WMyzJm6E6ux2KEl/2XsCZl+BNnnb7Q8bGQCS3ixF8r9d2ixHH5QgA5tbC4/AXTliw/8nmy9zzP0O/Ec2K1oBPrA8/ik2k12sYZtTN6SzZtu56zCYiqSrJkiBXnrjy2OsKwYwZ9wLsFk+Li0mjkU9vaT0cp4Dm3cVRp8rbPjFiiKn7CwxOm67vASTEdlQgLSvyCUWOhGZkOUJdWz67TWiswa7t9+Uz6+QonsAZsAyLBVC6Ma+rtmWiuDa+16srRIGr4/mzHhWOFwRRUyKjZBzy00P3Ek8ovIpv5o5pv22c4fA8rRHvecl8gNW9xMznJT+YhD9dhRR14+qnTUGI9J0fiysEXzawU1tTkyng1tmgH60lniWu3l678jMGs7OSxuq3UvrhrYEin5Q2nsRVKXtrewDV0lLJ/k+sgqE8EcAHWq8KaM2kl54+ofjgexnBdgVeomRPSxI3U3Ic2z3YvMVaBN+WL1wwAQAwzGdNa6xuzxWtEwstcRnK+yU1ogQvhoby0SGSfPgWpoaoryrS7+uz9AkdpQ1Fi8ihkSV6mrPfThq1ZoJueQ3sT7Ofueyu1tSQQcZnVwfr8fe/mc2tPv6h8QETwcRScp76HcVWACToXHIjaBjnd1v+4z8BGcXP0y772Psj0mZpKbywW2jthDAIsNIloX44oanRhdppzsodlBcemhVdkFY0auJAxNje6Ne3Rq4HwHU9d/QNeVSGVvMM9JGwbPmKtin8K8NLavJrQO9yxoLNtkQJS9/DwH4C4u7JTIxXsxioXg6RRD7ZYqEUnViRLZXRkGYiSRZlW05IJlZpPv+g2gJaz4INcIF/3iQwG/Ehfqy5E8Lbm/76DeWM2zTstFCjSx7qQonQNKZhxfjIV4Wmd+/r9wvlAcbnl7trru61U2eLhv2iGWm8FSaj/cl2SUlD/GfximMYYXJG42OGiGv3eu4MPrjMAARhXt35mYH+6rw0G9OM+fnn06N1YqYE2UdayNlBrXfZ7qQQ/seacTCQBr3xlx/fTa+M/slg9WYsA8zsZr5mMOCnfmg/TWI3bRfPLEuRmpT+t5R7z2Q95KYTdL3umVsCcepPbrPLU42xRb0kUZSNphczqgsy', 'j_idt32': ''}

POST Request -> Response =>

<Response [200]>
Mark: postResponse soup => 
<partial-response id="j_id1">
 <error>
  <error-name>
   class javax.faces.application.ViewExpiredException
  </error-name>
  <error-message>
   <![CDATA[viewId:/user/searchstatus.xhtml - View /user/searchstatus.xhtml could not be restored.]]>
  </error-message>
 </error>
</partial-response>
Table Soup =>

**Comment by anmolrajpal** [comment]
Their developers are probably calling some hidden script function for fetching data from their database. If somehow we can get the right listener, I hope this script will just work fine.

**Comment by chrisstone07** [comment]
Hi I've made a few changes to the script and managed to achieve the following response
------>

Mark: postResponse soup =>
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
 <changes>
  <update id="j_id1:javax.faces.ViewState:0">
   <![CDATA[I+C/uUSsfjq/50iD/qFdaGKV5QxUvq66kdwJHXmkdUcJRinvwCMZreJ/wVSZsABo0TiGaeQ6EPLyRVgrSgXQ3TVkT9oIjOzkSPdoYPlRbX/uCmONUmyhxqaG0zcZS0dLY0QjEYbKlkXUuFfxgrRs/xLYz6q5TzqH6hXNQlmFYMN7f/hoy/RRl//vGSDveP9/KM1hxBd3A07rLHhr1Rit6T9g1TEuHaZ9CcFUegjaaeM44ZhOPZAfeqdDeGfNc+/+78sSaui+4PCQs1zJnn4f1h6q1yZWr2UtDHSTqGRnziKGGYgP+hQ2OWeLagoH3m1tM+pEOh/0jDAaMwledIgIeGMF7VAEIhBTWbFTisDWZ3p6eYOrxUxIYvs3qK4vnyctx5ObCqSQLK+JIECfPljJT/qfkKpB82Knxn7G1/oEFIHBXLqhnmGgK13NaqpndNpg+O0qkrncDJuFnSGf2gWZHPZQTX0Zep+NbDWje2CfffsCKTrMcNERHx3mUIP4gb0+T74EiWJ665MqOQ6nWTwQjsuxFCaOEGY8MhNyvEam068c4rdeN56reiMv3PA/Kahe9BSmcjditfCpDLdI08rdzb7snVJT68hrvpx+oGqsmCPd3suPse332hZ00Yy32E2rWmI6tart2R1C52F2OKpveWgC+on4UYBJmi1I6oauN9XjbMnt96ZYhpc5uWE6e8P/LQrXRYoJq2n19o2gJ4X+ybIeaGw6om2QPK5xhUGVabKIU9fSsEpQ1JB4utsOkv9qs5WgwSw9UqJy5nUTAYHsl8MzpsqnfcCnk0RG0ba6yjMTkWH/kbFqUCAmYkDtgQy2NxcLo9wU1JfxyJZWvBhBxtSLiB8qcQ7fXsf6OsEJ7FC1SSDAhdXytSBPnuxIA2cuzjX8UgQX5c2r+PJ6g0/M2geh2dNwAdjLytE7lxHrbJdtCxjzlIoLvhlANPf+3KO+Bz5/lKY0G14toimUhqv7p5zB53XBX+RHRMhbCnw4ErL9kTZSyNwa15MMvey4r20IT4R/FhQEG7uwMw50fpXJ8T8L3ZiofqEi5zMIFsB0mt5hQ3eb5wzO3CTbIoFCLBdJM3hkDwKm0dq7oCVhJth/hZ+HHzQEGVRJUrhn/2SuQm7KOhTeRE0VIbveig9Ng7il]]>
  </update>
 </changes>
</partial-response>

Any clue of what this signifies?

**Comment by ushivam4u** [comment]
I am getting this while running:
 viewstate = soup.select('input[name="javax.faces.ViewState"]')[0]['value']
IndexError: list index out of range
how to solve it?

**Comment by anmolrajpal** [comment]
@ushivam4u It won't work. The web url has been changed by Government. So, no more playing with their services. Even I feel sad for wasting my time knowing that this day would come. I will eventually close this repository if I don't find another solution. By the way, thanks for your interest.
