### ISSUE TITLE
Resulting With Empty 

### ISSUE THREAD

**Issue by Pavithra3057** [anmolrajpal/vehicle-info#2]
Hi ,

   **I am getting empty result in "resultPanel". Please take n look and tell me what i have sent wrongly.**

Resolving Captcha
OCR Result =>  67V54N
67V54N
{'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Accept': 'application/xml, text/xml, */*; q=0.01', 'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'vahan.nic.in', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15', 'Cookie': 'JSESSIONID=2387DFA6222C790EA4751ECE2AC139DE.worker3; SERVERID_7081=vahanapi_7081; SERVERID_7082=nrservice_7082', 'X-Requested-With': 'XMLHttpRequest', 'Faces-Request': 'partial/ajax', 'Origin': 'https://vahan.nic.in', 'Referer': 'https://vahan.nic.in/nrservices/faces/user/searchstatus.xhtml', 'Connection': 'keep-alive'}

Cookie JSESSIONID =>  2387DFA6222C790EA4751ECE2AC139DE.worker3

Data =>

{'javax.faces.partial.ajax': 'true', 'javax.faces.source': 'j_idt45', 'javax.faces.partial.execute': '@ALL', 'javax.faces.partial.render': 'rcDetailsPanel resultPanel userMessages capatcha txt_ALPHA_NUMERIC', 'j_idt45': 'j_idt45', 'masterLayout': 'masterLayout', 'regn_no1_exact': 'MH04GM9660', 'txt_ALPHA_NUMERIC': '67V54N', 'javax.faces.ViewState': '8XV06TbojSxwZw+5LO/3tCklVXkwtMfIYvZcwqRPTZ0zP1GDIN97fswee0gF+Ll6KlafU69ZTYgpWUcoODJGMjg7ZM1niHca2PeE5LWZO/v2V34mKRvOG9JnoHhwJzBdAfQRTEbAk1jGRfKex6LeEjx0K3UClR4J6wKU51u5H1zU3xxXLwTfeDOcL84NoPP9S3+QyVuv33fwiupxycOF3tb0k1uNcpMt2dHRbLjnfT/a5786O5A/Sv/yZ4e1Kee/aTYUC6LmRAVXxoTjH5WAfoNQT4M2Vo5kpfDXFd8A+ahgzHc3V2njhkB+AB0FwXnRlLBgeofcD99q0tUvOVLWQWzIsarKkJ+xvmOFzIv2vA81Gyfw6Gryt7UQhtd2N/QLyKvDPXh8D2Aecw0ra4m6+oCTRlDCnInSBjmvROvqBw+WHGlcd8aMCxmes86yflLchdV5G3+i4HauCPAzfon4eyhduWik9dmmojG6GilIwsSPUZ3ZEtLWKPeVBSo/bpJgQ8FHTGRyR2CXoTEAmgR802ABks1kgnHgTMM7m02evu7XG/x+q3lcOik07MjhxQNWNEsDHLPD5yuqPlZsjP1MgvWPrCfLSzi9rF2SCApono+j5eoRoq7jVXaRXxEcPIpVsubq4UhSHNvQabse2uXSyngv5eGMCFpy1QvDk0hAzZohxBq60AlxXoQ09fm9obPIBjntzRNS1ygaTyh8S4HJCqMt1qzNPrqZ3KAB6fCzwsHhbE5LBNGieix+7BCSs//1WGaiemChO7289qWDz3CLJSTyQQ245GSf5gz3BGwLVa18l5UuTx00MeqD8EL4xnAOScTP3qYqXICkFQ3Zpl4expTV+NGffafxTDXW0QVPH7gSPnOXUjjj4h1TEkO3KQB4nWiVtJ5MrNlyBfrWfEZCwhsEkuCXyC8XoblHl2f8nNfOm+YpLBFQq5GGkN2B8ve4jbaHLyTyDNxKfwv9iaqGIgSsELf/3Yy3d8K6NDz1ethk3/+mpWDNjUFWJvkM6Wl+2kt8vhiuap5YHVMFPlNs/R8hMjcSyjUVnuPRcrHhhNZQaLqCDqWNIehz4wIJBKY0Q8UPxrHrwf2BoO5sJvwG9CYKFSKFvs2Cfuyiha2Ulmc8Bv6t52KeklK/xoddk7IV', 'j_idt36': ''}

POST Request -> Response =>

<Response [200]>
Mark: postResponse soup =>
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1">
 <changes>
  <update id="userMessages">
   <![CDATA[<div id="userMessages" class="ui-messages ui-widget error-message" aria-live="polite"></div>]]>
  </update>
  <update id="capatcha">
   <![CDATA[<div id="capatcha" class="ui-outputpanel ui-widget inline-section">
                                        <img alt="capatcha" src="/nrservices/cap_img.jsp" class="captcha-image" /></div>]]>
  </update>
  <update id="txt_ALPHA_NUMERIC">
   <![CDATA[<input id="txt_ALPHA_NUMERIC" name="txt_ALPHA_NUMERIC" type="text" value="" autocomplete="off" maxlength="10" size="8" class="ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all" /><script id="txt_ALPHA_NUMERIC_s" type="text/javascript">PrimeFaces.cw("InputText","widget_txt_ALPHA_NUMERIC",{id:"txt_ALPHA_NUMERIC"});</script>]]>
  </update>
  <update id="resultPanel">
   <![CDATA[<div id="resultPanel" class="ui-outputpanel ui-widget bottom-space"></div>]]>
  </update>
  <update id="j_id1:javax.faces.ViewState:0">
   <![CDATA[zC935mJAZfTqiyWQ1UNnN0DhYh+DjuHbt01x2Hbu/86dzsgAn1dWl1dCmgYurgKsI1U01HSdXTJ3aB+dwl/y6ra4Evv1qOh6sEfGN94eq+9fcJVqGcWXAPXGzIeWYhSBv4qxyXEx3hsxmIEhp8lOGnKRRR48SJfEJQQxtVsXQShZCjnS3SqWLhyw23MFbLic/cvbsTEE38bfVW8XlepbTDX6MDI79WYUOc218hXIGRPw488EsWjeCU7h7Lb/Z7NBtoVqnTwD3muXM2mIewWNli2Vbfrw5pWSec5hsD+CGVyHNNZ4A5bz1gqnIZUEwEhOXqzC5RVNgLqVgRBPUsxDghJaG+EuRmKAykPICOuz78eos9wUnIRCN+zx3iqRX6owIRkeanALXddmQ0AaW5TwzOWTYu89RQ886isyfhGawemvac23QswUFJO9484TTbeW9WixMM97YsI+eAsPLUIDaUfemkmcP8fP011jGxPM2hui0IGi+tfbnECS8vA2lPtLGlwLKV4S6YFK3rrNh83+uS+MsgfXUXVVryACprAEtg1UHUfrG0gzFgsWuWp2BQr6BEdtmuRdHodNGFM2BWI0fmxTNz88HZNbUmOWcI8rwp+GvtxKBOaljMiT89/gFxq+5h80HT6T8GkMo/Cp4oiucMkqu6+8zixtpsgFzn/Y/kuxfXfchFlkOaidlSua+I5vTAXHtlvgGXPbeU8iT5M0z2/12YxfU6Atg38SZiRWxIrtPgc0frN4ggEhjZW8Gi3blOoKvtyjO1kORRZ5koeq2x/QAhQTsM1UGDflxJQlXNc0ZdqaQjpk5lV49sH6WWsQZUOfx6i+1ivEUzY2RQSLWRMCzsQQAFraser7aptPvvfVMvthfuB5KZ9GjAKx/T6bG1ZcI3OYcRooO21b6jgj1/mHSFTepIugEJrf51Aef6wZhjBrlcKGV+B6lJiZHIX6T2Z3hf2IzY5krOA1OTCIFckLpR+g9MfwcGk3l8P3uoeq3TMnloWMEWuubvyMHXxE5cz7JZnrDZGFxMdoTKtGRMUbMBVc6O9yKRCOX0o8bG17my+YKFd9LTyb5YpdLK2P4Ca/4x73hJYWkHfYwUvNS5zjvqTA0DfTPlmP2ADf6VzzMdkHXcGuXMl/Q2/tQjkl]]>
  </update>
 </changes>
</partial-response>
Table Soup =>

**Comment by anmolrajpal** [comment]
Their developers are probably calling some hidden script function for fetching data from their database. If somehow we can get the right listener, I hope this script will just work fine.
