### ISSUE TITLE
output for your code

### ISSUE THREAD

**Issue by amarnath-jena** [anmolrajpal/vehicle-info#6]
sudo python vehical-info.py CH03X0301
Resolving Captcha
('OCR Result => ', u'Egkm66')
Egkm66
{'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Faces-Request': 'partial/ajax', 'Origin': 'https://vahan.nic.in', 'Accept': 'application/xml, text/xml, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15', 'Host': 'vahan.nic.in', 'Referer': 'https://vahan.nic.in/nrservices/faces/user/searchstatus.xhtml', 'Cookie': 'JSESSIONID=D36F14BEFF434810D56AD3E56AC4E341.worker3; SERVERID_7081=vahanapi_7081; SERVERID_7082=nrservice_7082', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'}
('\nCookie JSESSIONID => ', 'D36F14BEFF434810D56AD3E56AC4E341.worker3')

Data => 

{'javax.faces.ViewState': u'+TtSxQw1h8H0Du6qfwtBxLKvXSTecbGo/fvF7/0CrvafIVhekXl9JuW+R5HMVC/SKUlnRNtMIoeK8ko2/7YLmn0GO25lym+cIkiwukNDaYYk2P3bvnap3keajxC6doBM/A/eI++lwVE4e02tSa47LrweHQsxGX3DSaiuuU9Oe9Y+YohMusj/6rXeUtbelhhor9TNXBoYuM/ixGQazdnDMDwWawH5Q6BsrO64vbHcjfSP+9xHEfg/RpStgPUGHqDiHQfKx7S7soGBCYYyjSTPXp38m4FUiifeTSh8Nkd1lWAcofVPxWc5XUi/QlSgeRRt4L7vrEL11P1cIvvteguYMzP3N0/M3G35ynNJGQ9CmjcSiFuD0XKS32I3PrRzaI0MRPLpGyEokjAaxz2xRqzf8w+WHfIdQMU3Rw/OpmjInuLO3rRZIWbjwryJzmv9b+KHBAWiU7/zRb1EXoIDRdk3VAIScWSmgOmBzwdbUMFYY+apTjHZpcqNHUauGktrjQlb4O68IzHINVVjVxkiAsFRavVz9v5TlacgZG/Ky2dTslwKg607XgAiidqD9PIH+AycZ39lNaPU6P0gOMEVVFLjCUoeJaHGQqjKXQNMwyyzk3w/FVfXTRL450mUSpYHoH93WKVTRo1CGErEWAr4WPBBNtbjz41e3aJ9WTTwfQ/YtIJUgkLE7gXL4Ly7cAgl8I4PF8SVLVm5y0aAer3DpABdtfEtF5hacaeb34TAj7TGfkovjpGg2QdJU3IR/qJf00iI1FO3P5dp4siLxsTVNmtsI21+qoiS/2sRuxnrBqK4FK+UMtzPAqo90UXwtQW5EIx+6aQQZ+5XrjqJWpWaWXmVcVOZo88G2h9gt0hhvp1SxxBww7cmE3hOkbe5iFNMUSXHPbmy75be2fV5mw6MwQ/HGQtLaxsCeHzrCdyvp5DS6tc95uxY/Xj7kTNsf7CQQyb+vsPPG76vLv4zGxHqbOWQWG3BtTCa/AI2tOyvS18sE+ek8uPXiBWCDSjNbEIZFKwOUTrqwJx19vx/JTp7pnbg+WiklQrZuOV+tvYHzlZvV+sNI2ToM8G0n4L37cTjC8Ek67+LwLftnAOYYQa4PRJrT7WOOmflsfz8n34Q0AxamPflGw3rIKaLxPohZhkr8OiK', 'j_idt32': '', 'javax.faces.partial.render': 'rcDetailsPanel resultPanel userMessages capatcha txt_ALPHA_NUMERIC', 'txt_ALPHA_NUMERIC': u'Egkm66', 'javax.faces.partial.execute': '@all', 'javax.faces.source': u'j_idt45', 'masterLayout': 'masterLayout', 'javax.faces.partial.ajax': 'true', u'j_idt45': u'j_idt45', 'regn_no1_exact': 'CH03X0301'}

POST Request -> Response =>

<Response [200]>
Mark: postResponse soup => 
<partial-response id="j_id1">
 <error>
  <error-name>
   class javax.faces.el.EvaluationException
  </error-name>
  <error-message>
   <![CDATA[ ]]>
  </error-message>
 </error>
</partial-response>
Table Soup =>

**Comment by amarnath-jena** [comment]
i cant see any data for my vehical

**Comment by amarnath-jena** [comment]
How to run the script for bulk number of reg.nos from a .xlsx. Thanks for the script.

**Comment by mohitgupta3** [comment]
You can implement the script code as a class with the variable number as a function argument.
Then you may read the Excel file using pandas and run a for loop on the reg nos column.
